version: '3.8'

services:
  # PostgreSQL service
  postgres:
    image: postgres
    container_name: postgresql
    restart: always
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: cinema-ticket
    ports:
      - "5432:5432"

  # Golang application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cinema-ticket
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./config.json:/app/config.json
    ports:
      - "1323:1323"
